name: Deploy React App to GitHub Pages

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    # Defina permissões explicitamente
    permissions:
      contents: write
      pages: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: GENERATE_SOURCEMAP=false NODE_ENV=production npm run build
        env:
          CI: false
          DISABLE_ESLINT_PLUGIN: true
          INLINE_RUNTIME_CHUNK: false
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # Pasta que contém os arquivos de build
          branch: gh-pages # A branch onde serão publicados os arquivos
          token: ${{ secrets.DEPLOY_TOKEN }} # Usa o token de acesso pessoal
          clean: true # Limpa arquivos antigos
          force: true # Força o push para a branch gh-pages